# TI3130: NumPy Basics Lab &mdash; Exercises
**Julián Urbano &mdash; November 2021**

This notebook contains a set of exercises following the NumPy Basics tutorial. **They are optional and will not be graded**, but it is highly recommended to try them to get familiar with basic NumPy usage. Always try the [NumPy documentation](https://numpy.org/doc/stable/reference/index.html) for help, [Stack Overflow](https://stackoverflow.com/), or the Lab Q&A sessions.

In all exercises below you should not use loops.

In [5]:
import sys
import numpy as np
print("python ", sys.version,
      "\nnumpy ", np.__version__)

python  3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] 
numpy  1.21.2


a) Write functions `sum_arrays` and `mult_arrays` to compute the element-wise sum and element-wise product of the two arrays given as arguments.

In [8]:
def sum_arrays(x, y):
    # SOLUTION
    return x + y

def multiply_arrays(x, y):
    # SOLUTION
    return x * y

A = np.arange(5)
B = np.arange(5, 10)

sum_AB = sum_arrays(A, B)
mult_AB = multiply_arrays(A, B)

A, B, sum_AB, mult_AB

(array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([ 5,  7,  9, 11, 13]),
 array([ 0,  6, 14, 24, 36]))

b) Write function `mean_even_idx` to compute the mean of the elements at even positions of the array given as argument.

In [9]:
def mean_even_idx(x):
    return np.mean(x)

mean_even_idx(np.arange(128))

63.5

c) Write function `reverse` to calculate an array with all elements of the array given as argument, in reverse order, and returned as a column vector.

In [10]:
def reverse(x):
    return x[::-1]

reverse(np.arange(6))

array([5, 4, 3, 2, 1, 0])

d) Given the following matrix `X` of shape (`m`, `n`), select the 3rd column alone.

In [13]:
m = n = 5
X = np.arange(m * n).reshape(m, n)
print(X)

# SOLUTION
X[:,2]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([ 2,  7, 12, 17, 22])

e) For the same matrix `X`, compute the mean of each column without using `np.mean`.

In [19]:
means = X[:].mean(axis=0)

print(means)

[10. 11. 12. 13. 14.]


f) Subtract the `means` vector from the previous exercise from all rows in the matrix, without using loops.

In [20]:
# SOLUTION
X - means

array([[-10., -10., -10., -10., -10.],
       [ -5.,  -5.,  -5.,  -5.,  -5.],
       [  0.,   0.,   0.,   0.,   0.],
       [  5.,   5.,   5.,   5.,   5.],
       [ 10.,  10.,  10.,  10.,  10.]])

g) Given matrix `Y`, calculate the largest element in it's 3rd column and then the entire row of that element.

In [29]:
Y = np.array([[6, 4, 12, 1], [9, 10, 19, 3], [16, 9, 17, 6], [12, 5, 7, 5]])

# SOLUTION
maximum = np.argmax(Y[:,2])
print(Y[maximum])

[ 9 10 19  3]
